# Introdução e Objetivos

Este projeto apresenta uma análise exploratória dos dados do `Censo Demográfico 2022`, realizado pelo Instituto Brasileiro de Geografia e Estatística (IBGE). O Censo é a principal fonte de dados sobre a vida da população brasileira, oferecendo um retrato detalhado de quem somos, como vivemos e como o país mudou na última década.

Para esta análise, utilizamos os `Agregados por Municípios`, que consolidam informações socioeconômicas e demográficas das 5.570 cidades brasileiras. O foco principal é explorar a relação entre infraestrutura básica, educação e perfis demográficos, utilizando ferramentas de ponta em análise de dados.

## Objetivos Técnicos
Seguindo os padrões de rigor da Certificação Google Advanced Data Analytics, este notebook percorre o ciclo completo de análise:

- **ETL (Extração, Transformação e Carga)**: Processamento de arquivos brutos (.csv), tratamento de codificações e manipulação de grandes tabelas.

- **Data Wrangling**: Cruzamento de datasets temáticos (Merge) e renomeação técnica de variáveis com base em dicionários oficiais.

- **Análise Exploratória (EDA)**: Identificação de padrões, correlações e tratamento de valores ausentes (null values).

- **Visualização de Dados**: Criação de gráficos claros e informativos para comunicar insights geográficos e sociais.

## Estrutura PACE
**Para estruturar esse projeto utilizaremos a ESTRUTURA PACE (Plan, Analyze, Construct, Execute)**

### 1. Planejar (Plan)
**Foco:** Definição do escopo do projeto e as perguntas específica que queremos responder ao longo do projeto.
- Evolução demográfica por região. (Qual região teve maior crescimento vegetativo?) (O que indica determinado crescimento em determinada região?)
- Acesso à educação por estado. (Como a taxa de alfabetização varia entre diferentes regiões e tamanhos de municípios?)
- Relação entre Renda per capita x IDH. (Qual a relação entre Renda per capita e IDH?)
- Comparação entre as diferentes regiões do Brasil. (O que difere região X de região Y?)
- Existe correlação entre a infraestrutura domiciliar (rede de água e esgoto) e a densidade demográfica local?
- Qual o perfil de idade e sexo predominante nas regiões que mais cresceram desde o último Censo?
> O trabalho aqui será transformar esses temas amplos em perguntas de pesquisa específicas e factíveis com os dados que temos.

### 2. Analisar (Analyze)
**Foco:** Coleta, preparação e análise dos dados (Análise Exploratória de Dados - EDA)
- Importação de dados
- Limpeza
- reorganização
> O objetivo é avaliar a qualidade dos dados e descobrir padrões interessantes para o propósito do projeto.

### 3. Construir (Construct)
**Foco:** Criação de algoritmos de Machine Learning e Estatística
- Testes de hipóteses
- Modelos de Regressão Linear
> Realização de testes de hipótese para verificar se diferenças demográficas entre duas regiões são estatisticamente significativas ou apenas obra do acaso
> Construção de modelos de regressão linear para investigar a relação entre Renda per capita e IDH

### 4. Executar (Execute)
**Foco:** Entrega e apresentação dos resultados obtidos (Data Storytelling e Dashboards)
- Contar a história através dos números
- Dataviz utilizando Power BI e Tableau
> Apoiar decisões de negócios baseados nos dados

**Em resumo:**
- **Plan (Planejar)** → Define escopo, metas e necessidades do negócio.
- **Analyze (Analisar)** → Coleta, limpeza e EDA (Análise Exploratória).
- **Construct (Construir)** → Modelagem de Machine Learning e inferência estatística.
- **Execute (Executar)** → Apresentação de resultados e recomendações aos stakeholders.

## Link do conjunto de dados
[Conjuntos de dados IBGE - Censo 2022](https://www.ibge.gov.br/estatisticas/sociais/saude/22827-censo-demografico-2022.html?=&t=downloads)

# 1. Configuração do Ambiente e Importação

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 2. Exploração de Dados

In [5]:
df = pd.read_csv("../dados/brutos/Agregados_por_municipios_basico_BR.csv", sep=";", encoding="latin1")
df

,CD_MUN,NM_MUN,CD_REGIAO,NM_REGIAO,CD_UF,NM_UF,CD_NU,NM_NU,CD_AGLOM,NM_AGLOM,...,CD_CONCURB,NM_CONCURB,AREA_KM2,v0001,v0002,v0003,v0004,v0005,v0006,v0007
0,1100015,Alta Floresta D'Oeste,1,Norte,11,Rondônia,1100015001,Loteamento Canaã,.,NaN,...,.,NaN,"7067,1267819",21494,10081,10062,19,"2,8","0,0295",7699
1,1100023,Ariquemes,1,Norte,11,Rondônia,.,NaN,110002300015,Vila Rica,...,.,NaN,"4426,1431256",96833,44157,44114,43,"2,8","0,0438",34784
2,1100031,Cabixi,1,Norte,11,Rondônia,.,NaN,110003100004,Agrovila do PA Estrela do Oeste,...,.,NaN,"1314,3518453",5351,2927,2921,6,"2,7","0,0493",1967
3,1100049,Cacoal,1,Norte,11,Rondônia,1100049004,Casa de acolhimento são camilo,.,NaN,...,.,NaN,"3792,9997067",86887,40930,40905,25,"2,7","0,0257",31931
4,1100056,Cerejeiras,1,Norte,11,Rondônia,.,NaN,.,NaN,...,.,NaN,"2783,2970407",15890,7069,7064,5,"2,7","0,0393",5876
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,5222005,Vianópolis,5,Centro-Oeste,52,Goiás,.,NaN,522200500001,Ponte Funda,...,.,NaN,"954,1145323",14956,6815,6801,14,"2,7","0,0427",5503
5566,5222054,Vicentinópolis,5,Centro-Oeste,52,Goiás,.,NaN,522205400001,Palitozinho,...,.,NaN,"733,7942010",8768,3810,3797,13,"2,8","0,0214",3176
5567,5222203,Vila Boa,5,Centro-Oeste,52,Goiás,.,NaN,522220300001,Brasil Central,...,.,NaN,"1052,5933200",4215,1953,1944,9,"2,9","0,0129",1469
5568,5222302,Vila Propício,5,Centro-Oeste,52,Goiás,5222302001,Morro Nossa Senhora da Penha,.,NaN,...,.,NaN,"2181,5925482",5815,3212,3207,5,"2,7","0,0462",2184
5569,5300108,Brasília,5,Centro-Oeste,53,Distrito Federal,5300108039,Fazenda Sucupira,.,NaN,...,5300108,Brasília/DF,"5760,7825050",2817381,1172689,1172001,688,"2,8","0,0383",989344

# 3. Limpeza e Tratamento de Dados (ETL)

In [7]:
# transforma os espaços com "." ponto em NaN
df = df.replace('.', np.nan)
df

,CD_MUN,NM_MUN,CD_REGIAO,NM_REGIAO,CD_UF,NM_UF,CD_NU,NM_NU,CD_AGLOM,NM_AGLOM,...,CD_CONCURB,NM_CONCURB,AREA_KM2,v0001,v0002,v0003,v0004,v0005,v0006,v0007
0,1100015,Alta Floresta D'Oeste,1,Norte,11,Rondônia,1100015001,Loteamento Canaã,NaN,NaN,...,NaN,NaN,"7067,1267819",21494,10081,10062,19,"2,8","0,0295",7699
1,1100023,Ariquemes,1,Norte,11,Rondônia,NaN,NaN,110002300015,Vila Rica,...,NaN,NaN,"4426,1431256",96833,44157,44114,43,"2,8","0,0438",34784
2,1100031,Cabixi,1,Norte,11,Rondônia,NaN,NaN,110003100004,Agrovila do PA Estrela do Oeste,...,NaN,NaN,"1314,3518453",5351,2927,2921,6,"2,7","0,0493",1967
3,1100049,Cacoal,1,Norte,11,Rondônia,1100049004,Casa de acolhimento são camilo,NaN,NaN,...,NaN,NaN,"3792,9997067",86887,40930,40905,25,"2,7","0,0257",31931
4,1100056,Cerejeiras,1,Norte,11,Rondônia,NaN,NaN,NaN,NaN,...,NaN,NaN,"2783,2970407",15890,7069,7064,5,"2,7","0,0393",5876
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,5222005,Vianópolis,5,Centro-Oeste,52,Goiás,NaN,NaN,522200500001,Ponte Funda,...,NaN,NaN,"954,1145323",14956,6815,6801,14,"2,7","0,0427",5503
5566,5222054,Vicentinópolis,5,Centro-Oeste,52,Goiás,NaN,NaN,522205400001,Palitozinho,...,NaN,NaN,"733,7942010",8768,3810,3797,13,"2,8","0,0214",3176
5567,5222203,Vila Boa,5,Centro-Oeste,52,Goiás,NaN,NaN,522220300001,Brasil Central,...,NaN,NaN,"1052,5933200",4215,1953,1944,9,"2,9","0,0129",1469
5568,5222302,Vila Propício,5,Centro-Oeste,52,Goiás,5222302001,Morro Nossa Senhora da Penha,NaN,NaN,...,NaN,NaN,"2181,5925482",5815,3212,3207,5,"2,7","0,0462",2184
5569,5300108,Brasília,5,Centro-Oeste,53,Distrito Federal,5300108039,Fazenda Sucupira,NaN,NaN,...,5300108,Brasília/DF,"5760,7825050",2817381,1172689,1172001,688,"2,8","0,0383",989344

In [8]:
# Mostra a porcentagem de nulos em cada coluna
(df.isnull().sum() / len(df) * 100).sort_values(ascending=False)

NM_CONCURB    88.150808
CD_CONCURB    88.150808
CD_NU         66.642729
NM_NU         66.642729
NM_AGLOM      58.366248
CD_AGLOM      58.366248
CD_MUN         0.000000
NM_MUN         0.000000
CD_UF          0.000000
NM_UF          0.000000
CD_REGIAO      0.000000
NM_REGIAO      0.000000
NM_RGINT       0.000000
CD_RGINT       0.000000
NM_RGI         0.000000
CD_RGI         0.000000
AREA_KM2       0.000000
v0001          0.000000
v0002          0.000000
v0003          0.000000
v0004          0.000000
v0005          0.000000
v0006          0.000000
v0007          0.000000
dtype: float64

# 4. Análise Exploratória de Dados (EDA)

# 5. Visualização de Insights